Repository opendistro-for-elasticsearch/kibana-reports, pull requests merged in 2021-02, with the labels that each got.

#301 Change release workflows to use new staging bucket for artifacts
  .github/workflows/kibana-reports-release-workflow.yml
  .github/workflows/reports-scheduler-release-workflow.yml
Labels: build

#318 Add trouble shooting section to README
  README.md
  kibana-reports/rendering-engine/headless-chrome/README.md
Labels: documentation

#334 Bump Lodash version
  kibana-reports/package.json
  kibana-reports/yarn.lock
Labels: vulnerability

#336 Update Contributing.MD and PR Template
  .github/PULL_REQUEST_TEMPLATE.md
  kibana-reports/CONTRIBUTING.md
Labels: documentation
